### ISSUE TITLE
Themes Manager app Force Close

### ISSUE THREAD

**Issue by libnijunior** [libnijunior/patchrom_bullhead#2]
When try to open theme manager app it gives an force close

**Comment by libnijunior** [comment]
11-12 19:20:34.824  9526  9526 E AndroidRuntime: FATAL EXCEPTION: main
11-12 19:20:34.824  9526  9526 E AndroidRuntime: Process: com.android.thememanager, PID: 9526
11-12 19:20:34.824  9526  9526 E AndroidRuntime: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class miui.hybrid.HybridView
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.android.thememanager.h5.ThemeHybridFragment.onInflateView(ThemeHybridFragment.java:286)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.miui.internal.app.FragmentDelegate.onCreateView(SourceFile:146)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at miui.app.Fragment.onCreateView(SourceFile:62)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2220)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.Fragment.performStart(Fragment.java:2241)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1002)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:562)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.miui.internal.app.b.finishUpdate(SourceFile:308)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at miui.view.ViewPager.V(SourceFile:914)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at miui.view.ViewPager.dx(SourceFile:791)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at miui.view.ViewPager.onMeasure(SourceFile:1247)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.View.measure(View.java:18796)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.View.measure(View.java:18796)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.miui.internal.widget.ActionBarOverlayLayout.onMeasure(SourceFile:353)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.View.measure(View.java:18796)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.View.measure(View.java:18796)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class miui.hybrid.HybridView
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	... 46 more
11-12 19:20:34.824  9526  9526 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
11-12 19:20:34.824  9526  9526 E AndroidRuntime: 	... 51 more
11-12 19:20:34.824  9526  9526 E AndroidRuntime: Caused by: java.lang.Unsupp

**Comment by libnijunior** [comment]
Fixed on last patchrom update. #fc0e970
